version: '3.9'

services:
  # mongo:
  #   container_name: mongo_container
  #   image: 'mongo'
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - queue-net
  #   env_file: 
  #     - ./.env.production
  #   command: mongod --bind_ip_all
  #   restart: always

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: docker/production/Dockerfile
    ports:
      - '5173:80'
    restart: always
    env_file: 
      - ./.env.production
    depends_on:
      - server
    networks:
      - queue-net

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/production/Dockerfile
    ports:
      - '5000:5000'
    env_file: 
      - ./.env.production
    # depends_on:
    #   - mongo
    networks:
      - queue-net

networks:
  queue-net:
    driver: bridge

volumes:
  mongo-data:
